# Generated by Django 4.2.25 on 2025-11-01 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_movie_douban_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="likecomment",
            options={"verbose_name": "Click Like", "verbose_name_plural": "Click Like"},
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={"verbose_name": "Name", "verbose_name_plural": "Name"},
        ),
        migrations.AlterModelOptions(
            name="rate",
            options={
                "verbose_name": "Rating Information",
                "verbose_name_plural": "Rating Information",
            },
        ),
        migrations.AlterModelOptions(
            name="tags",
            options={"verbose_name": "Tag", "verbose_name_plural": "Tag"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "User"},
        ),
        migrations.AlterModelOptions(
            name="usertagprefer",
            options={
                "verbose_name": "User Preference",
                "verbose_name_plural": "Preference",
            },
        ),
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.CharField(max_length=255, verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user.movie",
                verbose_name="Movie",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user.user",
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="likecomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user.user",
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="collect",
            field=models.ManyToManyField(
                blank=True, to="user.user", verbose_name="Collector"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="country",
            field=models.CharField(max_length=255, verbose_name="Country"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="d_rate",
            field=models.CharField(max_length=255, verbose_name="Douban rating"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="d_rate_nums",
            field=models.IntegerField(verbose_name="Douban rating number"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="director",
            field=models.CharField(max_length=255, verbose_name="Director's Name"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="douban_id",
            field=models.CharField(max_length=128, null=True, verbose_name="Douban id"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="douban_link",
            field=models.URLField(verbose_name="Douban Link"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="image_link",
            field=models.FileField(
                max_length=255, upload_to="movie_cover", verbose_name="Cover pic"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="intro",
            field=models.TextField(verbose_name="Descriptions"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="leader",
            field=models.CharField(max_length=1024, verbose_name="Actors"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Movie Name"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="num",
            field=models.IntegerField(default=0, verbose_name="Views"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="origin_image_link",
            field=models.URLField(
                max_length=255, null=True, verbose_name="Douban Pictures Link"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="user.tags", verbose_name="tag"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="years",
            field=models.DateField(verbose_name="Release Time"),
        ),
        migrations.AlterField(
            model_name="rate",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Release Time"),
        ),
        migrations.AlterField(
            model_name="rate",
            name="mark",
            field=models.FloatField(verbose_name="Rating"),
        ),
        migrations.AlterField(
            model_name="rate",
            name="movie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.movie",
                verbose_name="Movie id",
            ),
        ),
        migrations.AlterField(
            model_name="rate",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.user",
                verbose_name="User id",
            ),
        ),
        migrations.AlterField(
            model_name="tags",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Tag"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Mailbox"),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=255, verbose_name="Password"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=255, unique=True, verbose_name="Account"),
        ),
        migrations.AlterField(
            model_name="usertagprefer",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user.tags",
                verbose_name="Tag",
            ),
        ),
        migrations.AlterField(
            model_name="usertagprefer",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.user",
                verbose_name="User id",
            ),
        ),
    ]
